var myName = "Sarah";
console.log(myName);
name1 = "Sarah AHmed";
console.log(name1);
var myAge = "22";
console.log(myAge);
var myQualification = "graduation";
console.log(myQualification);
var myFavColor = "Black";
console.log(myFavColor);
myFavColor = "Grey";
console.log(myFavColor);
var myHobby = "reading";
console.log(myHobby);
myHobby = "gardening";
console.log(myHobby);
